version: "3.9"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    container_name: backend-server
#    volumes:
#      - /ftas01/apps/HelpDesk/storage:/backend-server/storage:rw
#      - d:\dev\108bit\HelpDesk\storage\:/backend-server/storage:rw
    ports:
      - "8444:8444"
    restart: on-failure
    command: ["sh", "/backend-server/run.sh"]

  help_desk_bot:
    build:
      context: tg_bot
    env_file:
      - tg_bot/.env
    container_name:
      HelpDeskBot
    restart: always
    command:
      [ "python", "-u", "./start_bot.py" ]