version: "3.9"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    container_name: backend-server
#    volumes:
#      - /ftas01/apps/HelpDesk/storage:/backend-server/storage:rw
#      - d:\dev\108bit\HelpDesk\storage\:/backend-server/storage:rw
    ports:
      - "8443:8443"
    restart: on-failure
    command: ["sh", "/backend-server/run.sh"]