
login_url = 'auth/jwt/login'
logout_url = 'auth/jwt/logout'
tg_user_role_url = 'telegram/tg-user-role'
tg_user_appeal_params_url = 'telegram/tg-user-appeal-params'
tg_create_appeal_url = 'telegram/tg-create-appeal'
tg_update_appeal_chanel_post_id_url = 'telegram/tg-update-appeal-chanel-post-id'
contacts_url = 'telegram/contacts'
tg_get_appeals_url = 'telegram/tg-get-appeals'
tg_close_appeal_url = 'telegram/tg-close-appeal'
tg_appeal_add_photo_url = 'telegram/tg-appeal-add-photo'
