"""Change tables users

Revision ID: 07b7ca896613
Revises: fc26164dd044
Create Date: 2024-06-09 10:39:06.560898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b7ca896613'
down_revision: Union[str, None] = 'fc26164dd044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_phone_number_key', 'users', type_='unique')
    op.drop_constraint('users_tg_phone_number_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'tg_id')
    op.drop_column('users', 'username')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'tg_phone_number')
    op.drop_column('users', 'is_system_admin')
    op.drop_column('users', 'is_system_bot')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_system_bot', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_system_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('tg_phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('tg_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_tg_phone_number_key', 'users', ['tg_phone_number'])
    op.create_unique_constraint('users_phone_number_key', 'users', ['phone_number'])
    # ### end Alembic commands ###
