"""create object description

Revision ID: 34df2f7bd778
Revises: 192d7de0bd4e
Create Date: 2024-06-30 14:37:09.644091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34df2f7bd778'
down_revision: Union[str, None] = '192d7de0bd4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object', 'description')
    # ### end Alembic commands ###
