"""create object name unique

Revision ID: 3b1b94eaedb8
Revises: 34df2f7bd778
Create Date: 2024-06-30 15:32:17.043431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b1b94eaedb8'
down_revision: Union[str, None] = '34df2f7bd778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'object', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'object', type_='unique')
    # ### end Alembic commands ###
