"""Change table users

Revision ID: 4f4578713dc6
Revises: 84811ec64dbd
Create Date: 2024-06-08 21:29:50.098286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f4578713dc6'
down_revision: Union[str, None] = '84811ec64dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('is_system_bot', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_system_admin', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'users', ['tg_phone_number'])
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'is_system')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_system', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'is_system_admin')
    op.drop_column('users', 'is_system_bot')
    op.drop_column('users', 'tg_phone_number')
    # ### end Alembic commands ###
