"""change table name UserOrganization

Revision ID: fc2ddead7de2
Revises: 144dd83688fb
Create Date: 2024-07-04 16:52:57.417974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc2ddead7de2'
down_revision: Union[str, None] = '144dd83688fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users_organizations', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_organizations', type_='unique')
    # ### end Alembic commands ###
