version: "3.7"
services:
  help_desk_bot:
    build:
      context: .
    env_file:
      - .env
    container_name:
      HelpDeskBot
    restart: always
    command:
      ["python", "-u", "./start_bot.py"]